[package]
name = "pista"
version = "0.1.0"
authors = ["NerdyPepper <akshayoppiliappan@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
tico = "1.0.0"
libc = "0.2.55"
colored = "1.8.0"
git2 = "0.8.0"
clap = "2.33.0"
